### ISSUE TITLE
Meta issue: Remove deprecated calls, and small breaking changes

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#2024]
- [ ] Remove the deprecated warnings in the .slint languages
 - [x] Remove deprecated functions in the API
 - [x] Other breaking changes in the API
    - [x] #1953
    - [x] #1943
    - [x] #1903
    - [x] #1749
 - ...

**Comment by tronical** [comment]
I noticed the following inconsistency in the `index` row parameter in C++ `slint::VectorMode`:

```cpp
    void erase(int index);
    void insert(size_t index, const ModelData &value);
```

Should `insert` take an `int` instead, should `erase` take a `size_t`, or should we leave it as-is? If it's one of the first time, then I'll create an issue - just wanted to check here first.

**Comment by ogoffart** [comment]
We should fix it so it is consistent.   
I was first thinking it should be size_t like for std::vector.
But then i saw that all the row of models are `int` currently., so we'd need to change them all if we wanted to.
(In rust it is `usize`)

**Comment by tronical** [comment]
> Remove the deprecated warnings in the .slint languages

There are still quite a few of those left in the compiler. I guess this also still needs to be done before the release then.

**Comment by ogoffart** [comment]
Some remaining warnings:

Only warning with the old syntax:
```
internal/compiler/expression_tree.rs:                        ctx.diag.push_warning("Modifying a property that is linked to a read-
internal/compiler/expression_tree.rs:                        .push_warning(format!("{what} on an output property is deprecated"), 
internal/compiler/object_tree.rs-                        format!("Assigning to output property '{unresolved_name}' is deprecated"),
internal/compiler/passes/resolving.rs-                                                    "Link to a {} property is deprecated",
```

These were added fairly recently:
```
internal/compiler/object_tree.rs-                    "Component is neither used nor exported".into(),
internal/compiler/object_tree.rs-                        "Global singleton is implicitly marked for export. This is deprecated and it should be explicitly exported"
internal/compiler/object_tree.rs:                    diag.push_warning("Component is implicitly marked for export. This is deprecated and it should be explicitly exported".into(), &last_compo.node)
```


Should that be errors?

```
internal/compiler/object_tree.rs-                            "'{}' is already exported in this file; it will not be re-exported",
internal/compiler/passes/embed_glyphs.rs-                            format!("Could not load the font set via `SLINT_DEFAULT_FONT`: internal/compiler/passes/embed_glyphs.rs-                    "The environment variable `SLINT_DEFAULT_FONT` is set, but its internal/compiler/passes/embed_glyphs.rs:                diag.push_warning_with_span(format!("could not find font that provides specified family, falling back to Sans-Serif"), source_location);
internal/compiler/passes/embed_images.rs:                diag.push_warning(format!("Cannot find image file {}", path), source_location);
```

I think this should stay warning as it would prevent a preview of sub-component?

```
internal/compiler/passes/lower_property_to_element.rs-                "The {} property cannot be used on the root element, it will not be applied",
internal/compiler/passes/lower_shadows.rs-            format!("The {} property cannot be used on the root element, the shadow will not be visible", shadow_prop_name),
internal/compiler/passes/visible.rs-            "The visible property cannot be used on the root element, it will not be applied"
```
