### ISSUE TITLE
C++ API for MCU

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#2136]
With Slint 0.3, we released the platform API for Rust that allows to use the software renderer from a MCU.
But we postponed the work for C++.
This summarize what is left to do.
Some WIP prototype is in the `olivier/wip/mcu_cpp` branch

## Milestone 1:  C++ on MCU using a Slint platform written in Rust

 - [x] ~~create a main.cpp and CMakeLists.txt file in the printerdemo_mcu folder~~ Created esp-idf component and examples using it.
 - [x] make api/cpp  no_std and ability to remove all dependencies we don't need
 - ~~[ ] add a function to the mcu_board_support crate to initialize the MCU backend. Use it from api/cpp~~
 - [x] add #ifdefs in slint.h for the unsupported stuff on MCU  (iostream, thread, and the like)
 - [x] Do the right incentation to get CMake generate a static lib
 - [x] Serialize the bitmap fonts to C++ datastructure in `generator/cpp.rs`
 - [x] Get cmake to cross compile for such devices

## Milestone 2: Platform in C++

 - [x] Complete and stabilize the experimental slint_platform.h and `slint::experimental::platform` namespace.  Most of the API in there still relies on raw cbindgen enums for which we need to write a good C++ API
