### ISSUE TITLE
Initial Python Module (Milestone #1)

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#4161]
This umbrella issue tracks the first milestone to enable dynamic loading of Slint UIs from “.slint” files in Python code.

Sub-tasks:

 - [ ] https://github.com/slint-ui/slint/issues/4133
 - [ ] https://github.com/slint-ui/slint/issues/4134
 - [ ] https://github.com/slint-ui/slint/issues/4135

**Comment by tronical** [comment]
Silly me, let's use a milestone instead (https://github.com/slint-ui/slint/milestone/18 )
