### ISSUE TITLE
Node.js: Remove the beta label

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#4471]
At the moment the Node.js integration is labelled beta. This issue tracks - on a high level - the issues that we should resolve before removing the beta label:

 - [ ] https://github.com/slint-ui/slint/issues/4469
 - [ ] Equivalent API compared to Rust and C++ (https://github.com/slint-ui/slint/issues/4470)
 - [x] Snippets in the docs that mention Rust and C++ should also mention Node.js (such as https://slint.dev/releases/1.4.1/docs/slint/src/advanced/style#selecting-a-widget-style )
 - [x] Add support for translations and extend https://slint.dev/releases/1.4.1/docs/slint/src/language/concepts/translations#select-and-load-mo-files-at-run-time ?
 - [ ] Decide how to expose and document colors we expose from Slint (as opposed to what we accept as input): https://github.com/slint-ui/slint/issues/4689
 - [x] Add support for setting enums declared in Slint from JavaScript (such as `sort_order` in `TableColumn`)
 - [ ] make fileLoader callback return a promise #6539
