### ISSUE TITLE
Initial Android Support

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#46]
This project is funded through NGIO Core via NLNet - https://nlnet.nl/project/SlintAndroid/

Here's a possible breakdown of tasks that we devised. We estimate this in the range of ~4 months of work.

1. Base Android Port Milestone. This milestone covers the foundation of the port, to allow for the cross-compilation of a Rust based Slint application, deployment to a device, and showing primitive graphics on the screen, including text labels. Rendering is to be done with Skia, for GPU acceleration and native looking text rendering.
  - [x] Create or modify an existing example to cross-compile and deploy to the device, re-using existing crates and functionality in the Rust ecosystem. 
  - [x] Set up the CI system to test the build (and optionally deployment to the emulator).
  - [x] #3430
  - [x] Document how users can write applications for Android using Slint (https://slint.dev/snapshots/master/docs/rust/i_slint_backend_android_activity/)
2. Text Input Integration Milestone. This milestone covers the work to allow the user to interact with text input fields in Slint in a way that is consistent with other Android applications.
 - [x] Show or hide the Android system virtual keyboard depending on focus on text input fields.
 - [x] Ensure visibility of text input fields when focused and the virtual keyboard occupies a part of the screen. This includes scrolling and resizing the user interface.
 - [x] Add support for text selection handles by rendering them at the correct location and allowing the user to interact with them way.
3. Dialog and Menu Widgets. This milestone will add first-class support for Material Design Dialog and Menu components. Dialogs in general and Menus specifically are crucial for many application workflows on Android.
 - [ ] Add support for dialog components in the material design style and rendering them in a way that makes them appear like native dialogs.
  - [x] Add support for declaring menu structures in the Slint language, rendering them with the material design style, and obtaining the user-selected menu item choice in native code.
4. Date and Time Picker Widgets. This milestone will add support for Date and Time picker widgets, for use in dialogs. Both user interface elements represent complex controls and data models, due to different time zones and localization.
 - [x] Add support for a widget in the material design style to allow the user to select a date, based on the system calendar and an optional provided input date.
  - [x] Add support for a widget in the material design style for picking a time, based on the system time and an optional provided input time.

--- 

**Update:** Check the documentation to try the android backend: https://docs.rs/slint/latest/slint/android/index.html

**Comment by Berrysoft** [comment]
Is there any progress here? I've found that both `winit` and `glutin` has Android support.

**Comment by ogoffart** [comment]
Not really. There is some work in progress to make it compile in the [`olivier/wip/android` branch](https://github.com/slint-ui/slint/commit/3801345fb879e6b68a2fc5067c86cc75a653936d), but it doesn't work yet. Some more work will be needed to adjust the way the window is initialized.

**Comment by Skilvingr** [comment]
Hi, I've forked @ogoffart 's repo and I've finally managed to build a working `printerdemo` example [here](https://github.com/Skilvingr/slint/commits/skilvingr/android) by using [cargo-apk](https://crates.io/crates/cargo-apk).

The main issues I've had to solve are:

1. delaying the initialisation of the window, until the event loop receives a `InitWindow` event (which means that Android is ready to create it):
The fastest (and obviously not the most elegant) way is to block `android_init` using a loop. (the path I've taken)
The best way would probably be to make surface, gl context and other stuff optional, as other projects have already done.

2. disable `fontconfig`, as the ndk doesn't ship a bundled version and Android seems to ignore every self-compiled library one adds to the apk:
If I've understood correctly the code I've read, the same thing is done for wasm32 builds.

Overall, everything seems to work decently (considering that this was a test), apart from the fact that, as soon as one tries to switch app, Android destroys context and surface and the application crashes (for the same reason of point 1.).
![Screenshot_20230601_174645](https://github.com/slint-ui/slint/assets/42282906/cd8931b8-07cc-41b7-9d9d-31a4664ac493)

I hope this will help to speed up the development. Thank you for your work!

**Comment by tronical** [comment]
Great work!

**Comment by tronical** [comment]
One aspect that might need support in the run-time library APIs or perhaps even the .slint language is first-class support for the [Android Activity Lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle). The [Android Activity Crate](https://docs.rs/android-activity/latest/android_activity/enum.MainEvent.html) supports these state events, and we may want to integrate this with callbacks to the application - ideally in a platform independent way that the same API could be used also on iOS.

**Comment by tronical** [comment]
We've made an initial plan for how we'd like to break down the Android port and I'd like to share it here for further editing/discussion. I'll edit the current empty description of this issue for that purpose.

**Comment by calvin2021y** [comment]
Is there a roadmap or  plan with timetable for mobile support?

**Comment by tronical** [comment]
> Is there a roadmap or plan with timetable for mobile support?

We have not made a plan beyond the breakdown and time estimate outlined in the description of this issue. We want to learn from the Android port first and then have a better idea about what additional functionality and features we need to support also iOS and mobile specific features in general. This initial work on Android is also limited to Rust as target programming language.

**Comment by moolight-seashell** [comment]
is there a way to build an android widget component in slint ?

**Comment by wuanzhuan** [comment]
I'm interested in using Slint with Node.js for Android development. Is this combination currently supported on Android? If not, is there a roadmap or expected release date for Android compatibility?

**Comment by MCorange99** [comment]
Im intrrested in how this is going, id genuinely have some great ideas for applications where i could use slint

**Comment by ogoffart** [comment]
It's been a while since we have had "initial android support", so closing this issue now.

**Comment by Nicolas5241** [comment]
what would be the minimum supported android version?

**Comment by ogoffart** [comment]
I believe Android 9
