### ISSUE TITLE
Qt backend meta issue

### ISSUE THREAD

**Issue by notfirefox** [slint-ui/slint#5017]
This issue will be used to track the state of the qt backend.

**Button**
- [ ] Do not activate on enter

**CheckBox**
- [ ] Do not activate on enter

**ComboBox**
- [x] Implement `has_focus` ([#5061](https://github.com/slint-ui/slint/pull/5061))
- [x] Fix key navigation ([#4826](https://github.com/slint-ui/slint/issues/4826))

**GroupBox**
Good

**LineEdit**
- [ ] Implement `has_hover`
- [ ] Fix color of text selection highlighting 

**ListView**
Good

**ProgressIndicator**
Good

**ScrollView**
- [ ] Implement `has_hover`
- [ ] Check if the left mouse button was used
- [x] Only show scroll bars when necessary ([#3552](https://github.com/slint-ui/slint/issues/3552))

**Slider**
- [ ] Fix behavior when starting drag from anywhere but the slider handle
- [ ] Implement `has_hover`

**Spinbox**
- [ ] Implement `has_hover`
- [ ] Make spinbox editable ([#4690](https://github.com/slint-ui/slint/issues/4690))
- [ ] Allow increasing/decreasing by click and hold event ([#3051](https://github.com/slint-ui/slint/issues/3051))

**TableView**
Good

**TabWidget**
- [ ] Implement `has_hover` ([#4974](https://github.com/slint-ui/slint/issues/4974))
- [x] Allow scrolling through tabs using mouse wheel ([#5002](https://github.com/slint-ui/slint/issues/5002))

**TextEdit**
- [ ] Highlight selected text

**Comment by ogoffart** [comment]
Please note that the behavior should ideally be the same as the widgets from the other style. (unless there are reason for it to diverge, such as platform specific behavior or so)

**Comment by notfirefox** [comment]
> Please note that the behavior should ideally be the same as the widgets from the other style. (unless there are reason for it to diverge, such as platform specific behavior or so)

On the KDE Plasma desktop and all Qt applications I have used so far, buttons checkboxes and comboboxes do not activate when pressing the enter key. Is that a Windows or macOS thing?

Furthermore on the KDE Plasma desktop and in other Qt applications, widgets such as comboboxes _do open_ with the space key, this is _expected behavior_. 

Currently comboboxes only open with the enter key but buttons and checkboxes open with _both_ space and enter. This is somewhat inconsistent.

**Comment by ogoffart** [comment]
> On the KDE Plasma desktop and all Qt applications I have used so far, buttons checkboxes and comboboxes do not activate when pressing the enter key. Is that a Windows or macOS thing?

This is a slint bug. See also https://github.com/slint-ui/slint/issues/4826
Qt is most likely right, but we should still check on Windows and Mac and make sure that the fluent and cupertino and cosmic style also behave properly according to their platform.

Of course it is better to have the Qt style fixed even if the other style are not fixed.
