### ISSUE TITLE
Request for Support System Tray Icon

### ISSUE THREAD

**Issue by ArcticLampyrid** [slint-ui/slint#6053]
While there are several excellent tray icon libraries available for Rust, they often pose challenges when integrated with Slint. These libraries may introduce heavy dependencies (e.g., GTK), conflict with Slint's event loop, or come with other drawbacks. 

To ensure a smoother experience, it may be more advantageous for Slint to provide native APIs for tray icon support.

Additionally, C++ users would benefit from this, as there is a lack of standalone and actively maintained tray libraries for C++ (if there are any, please let me know). In fact, we are considering introducing Qt as a dependency solely for cross-platform tray support.

**Comment by ogoffart** [comment]
I think we'll indeed need to tackle this problem in Slint at some point.

**Comment by ogoffart** [comment]
We should try to find a rust crate that offer this feature and encapsulate it in a Slint API.

One idea would be to have the API look like this using a top level component.

```slint
export MyTray inherits SystemTray {
   icon: MyLogic.is_active ? @image-url("...");
   tooltip: ...
   Menu {
      MenuItem { ... }
   }
   clicked(event) => { ... // how to access other parts of the application? }
}
```
Then the programming language
```rust
let my_tray = MyTray::new().unwrap();
my_tray.on_clicked(...) ??
my_tray.show();
```

But that API still needs to be iterated over.

**Comment by ruffsl** [comment]
Indeed the ksni crate is great, and very light weight! Linux platform specific though, and best supported yet by KDE:

- https://github.com/ruffsl/CtrlAssist/blob/e003497914a4197b683db818e4d4ea97636d1ea0/src/tray/app.rs#L371

<img width="1280" height="640" alt="Image" src="https://github.com/user-attachments/assets/806f07c8-db74-457f-8967-e2cd62dc2b63" />

**Comment by expenses** [comment]
We probably want to use the tauri tray-icon crate for most backends: https://crates.io/crates/tray-icon

Would be nice to use ksni instead situationally though

**Comment by ogoffart** [comment]
> We probably want to use the tauri tray-icon crate for most backends: https://crates.io/crates/tray-icon

Right, although i'm not a fan of the gtk dependency. (that has caused problem in the past when we when muda had a hardcoded gtk dependency).
So perhaps tray-icon on windows and mac, and ksni on linux would work.

**Comment by expenses** [comment]
Todo:

- [x] Have some kind of integration with slint code via a `SystemTray` component
- [x] System tray event handling 
- [x] Menus via slint types - https://github.com/slint-ui/slint/pull/11481
- ~~[ ] Get https://github.com/tauri-apps/tray-icon/compare/dev...expenses:tray-icon:optional-gtk merged ~~
- [x] Tests 
- [x] Documentation - https://github.com/slint-ui/slint/pull/11496 but needs a final review to make sure that everything is documented (clicked, etc.)

Remaining Todo is now in the tracking PR #11574

**Comment by tronical** [comment]
We discussed the shape of the Rust/C++/Node.js/Python API for this and concluded:

- For Rust, the generated code for a SystemTray sub-class will have associated methods (`as_weak`, `clone_strong`, `show`, etc. but no `window() accessor)
- For the interpreter, we'll generate regular `ComponentDefinition` and `ComponentInstance`. Calling `window()` will unfortunately panic.
- For Node.js and Python we should make sure that there's no `window` property.
- The fact that globals are disconnected from other globals is something we should mention in the docs - it's just like exporting multiple windows.

**Comment by tronical** [comment]
Regarding the tray-icon dependency: We're basically waiting for https://github.com/tauri-apps/tray-icon/pull/305 and https://github.com/tauri-apps/tray-icon/pull/304 to be included in a new release. We need those to avoid duplicate dependencies to muda and to avoid the repo wide security warnings due to Gtk in our lock file. Meanwhile, the plan is to have appkit and win32 direct implementations.
