### ISSUE TITLE
1.9 Documentation tracking issue

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#6830]
- [ ] Guide is unfinished.
- [ ] Enable the full link validator that is currently disabled due to all the link issues in the auto generated enums and structs.
- [ ] Generate Time and date stuct files from the std-widgets code.

## Nice to have / Future enhancements
- [ ] Multi property component. The current <SlintProperty> component works for single items. It would help to have one where tightly related items can be grouped e.g. width and height, x, y, z etc.

**Comment by xb284524239** [comment]
I suggest adding a section about the changelog in the documentation of version 1.9. In this way, users can easily know what changes each upgrade has brought.
